[
  { "name": "Layla", "role": "Gold Lane" },
  { "name": "Miya", "role": "Gold Lane" },
  { "name": "Granger", "role": "Gold Lane" },
  { "name": "Claude", "role": "Gold Lane" },
  { "name": "Bruno", "role": "Gold Lane" },
  { "name": "Beatrix", "role": "Gold Lane" },
  { "name": "Moskov", "role": "Gold Lane" },
  { "name": "Brody", "role": "Gold Lane" },
  { "name": "Lesley", "role": "Gold Lane" },
  { "name": "Popol and Kupa", "role": "Gold Lane" },
  { "name": "Wanwan", "role": "Gold Lane" },
  { "name": "Karrie", "role": "Gold Lane" },
  { "name": "Irithel", "role": "Gold Lane" },
  { "name": "Hanabi", "role": "Gold Lane" },
  { "name": "Melissa", "role": "Gold Lane" },

  { "name": "Tigreal", "role": "Roamer" },
  { "name": "Franco", "role": "Roamer" },
  { "name": "Lolita", "role": "Roamer" },
  { "name": "Akai", "role": "Roamer" },
  { "name": "Atlas", "role": "Roamer" },
  { "name": "Grock", "role": "Roamer" },
  { "name": "Khufra", "role": "Roamer" },
  { "name": "Minotaur", "role": "Roamer" },
  { "name": "Belerick", "role": "Roamer" },
  { "name": "Estes", "role": "Roamer" },
  { "name": "Angela", "role": "Roamer" },
  { "name": "Faramis", "role": "Roamer" },
  { "name": "Mathilda", "role": "Roamer" },
  { "name": "Diggie", "role": "Roamer" },

  { "name": "Lancelot", "role": "Jungle" },
  { "name": "Hayabusa", "role": "Jungle" },
  { "name": "Helcurt", "role": "Jungle" },
  { "name": "Ling", "role": "Jungle" },
  { "name": "Gusion", "role": "Jungle" },
  { "name": "Karina", "role": "Jungle" },
  { "name": "Fanny", "role": "Jungle" },
  { "name": "Roger", "role": "Jungle" },
  { "name": "Yi Sun-shin", "role": "Jungle" },
  { "name": "Aamon", "role": "Jungle" },
  { "name": "Julian", "role": "Jungle" },
  { "name": "Saber", "role": "Jungle" },

  { "name": "Esmeralda", "role": "XP Lane" },
  { "name": "Uranus", "role": "XP Lane" },
  { "name": "Yu Zhong", "role": "XP Lane" },
  { "name": "Benedetta", "role": "XP Lane" },
  { "name": "Lapu-Lapu", "role": "XP Lane" },
  { "name": "Dyrroth", "role": "XP Lane" },
  { "name": "Thamuz", "role": "XP Lane" },
  { "name": "Paquito", "role": "XP Lane" },
  { "name": "X.Borg", "role": "XP Lane" },
  { "name": "Phoveus", "role": "XP Lane" },
  { "name": "Freya", "role": "XP Lane" },
  { "name": "Terizla", "role": "XP Lane" },
  { "name": "Baxia", "role": "XP Lane" },

  { "name": "Lunox", "role": "Mid Lane" },
  { "name": "Valentina", "role": "Mid Lane" },
  { "name": "Pharsa", "role": "Mid Lane" },
  { "name": "Yve", "role": "Mid Lane" },
  { "name": "Kagura", "role": "Mid Lane" },
  { "name": "Lylia", "role": "Mid Lane" },
  { "name": "Harith", "role": "Mid Lane" },
  { "name": "Xavier", "role": "Mid Lane" },
  { "name": "Cecilion", "role": "Mid Lane" },
  { "name": "Eudora", "role": "Mid Lane" },
  { "name": "Cyclops", "role": "Mid Lane" },
  { "name": "Vale", "role": "Mid Lane" },
  { "name": "Odette", "role": "Mid Lane" },
  { "name": "Gord", "role": "Mid Lane" },

  { "name": "Nolan", "role": "Jungle" },
  { "name": "Fredrinn", "role": "Roamer" },
  { "name": "Joy", "role": "Mid Lane" },
  { "name": "Leomord", "role": "XP Lane" },
  { "name": "Alpha", "role": "XP Lane" },
  { "name": "Badang", "role": "XP Lane" },
  { "name": "Minsitthar", "role": "Roamer" },
  { "name": "Zhask", "role": "Mid Lane" },
  { "name": "Jawhead", "role": "Roamer" },
  { "name": "Barats", "role": "Jungle" },
  { "name": "Floryn", "role": "Roamer" }
]