name: Ping Server Every 15 Minutes (Tehran Time)

on:
  schedule:
    - cron: '*/15 4-20 * * *'  # هر 15 دقیقه از 8 صبح تا 12 شب به وقت ایران (UTC+3:30)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl the server
        run: curl -fsS --retry 3 https://my-bot-xc37.onrender.com || echo "Server not reachable"